### ISSUE TITLE
Feedback when trying `skore.Project` and `CrossValidateReporter`

### ISSUE THREAD

**Issue by glemaitre** [probabl-ai/skore#1006]
So I give a first try to `skore.Project`, `skore.CrossValidateReporter`, and the `skore-UI`.

Here come my minimal toy example:

```python
# %%
import skore

project = skore.create(project_name="project", overwrite=True)

# %%
from skore import CrossValidationReporter
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold

X, y = load_iris(return_X_y=True)
model = LogisticRegression()

reporter = CrossValidationReporter(model, X, y, cv=5)
project.put("cv-report", reporter)
```

So here, I get the several issue

### Issue 1: computation of undesired metrics

I get a long list of warning by the internal cross-validation:

<details>

```shell
[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:978](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py#line=977): UserWarning:

Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 140](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=139), in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 388](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=387), in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 216](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py#line=215), in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py", line 3013](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py#line=3012), in log_loss
    raise ValueError(
ValueError: y_true and y_pred contain different number of classes 3, 2. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [0 1 2]


[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py#line=464): ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:978](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py#line=977): UserWarning:

Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 140](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=139), in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 388](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=387), in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 216](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py#line=215), in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py", line 3013](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py#line=3012), in log_loss
    raise ValueError(
ValueError: y_true and y_pred contain different number of classes 3, 2. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [0 1 2]


[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:978](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py#line=977): UserWarning:

Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 140](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=139), in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 388](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=387), in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 216](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py#line=215), in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py", line 3013](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py#line=3012), in log_loss
    raise ValueError(
ValueError: y_true and y_pred contain different number of classes 3, 2. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [0 1 2]


[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:978](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py#line=977): UserWarning:

Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 140](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=139), in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 388](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=387), in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 216](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py#line=215), in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py", line 3013](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py#line=3012), in log_loss
    raise ValueError(
ValueError: y_true and y_pred contain different number of classes 3, 2. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [0 1 2]


[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:978](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/model_selection/_validation.py#line=977): UserWarning:

Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 140](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=139), in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 388](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_scorer.py#line=387), in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 216](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/utils/_param_validation.py#line=215), in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py", line 3013](http://localhost:8890/Users/glemaitre/Documents/scikit-learn-workspace/src/skore/.pixi/envs/dev/lib/python3.12/site-packages/sklearn/metrics/_classification.py#line=3012), in log_loss
    raise ValueError(
ValueError: y_true and y_pred contain different number of classes 3, 2. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [0 1 2]
```

</details>

So basically the computation of the `logloss` failed because a corner case because we are not predicting one of the class (I have to check if it the case).

So in terms of UX, I have potentially 2 ways that I would like to go:

- `skore` should not bother me with the computation of the `logloss` because I did not ask anything about it. It could be argued that it is a sensible default and documented when `scoring` is `None` which is not the case for the moment because it refers to the scikit-learn documentation. If we argue that `skore` should not compute for me this metric, then what we want as a feature is an aggressive caching mechanism as used in #997: we need to store the predictions of the response methods whenever a user triggered it in some way.
- if `skore` decide to still pre-compute some not requested metric, then we need to make sure that we don't have any corner case and that we always can compute the metric. It means that we might think about missing classes in classification and editorial choice regarding the default for the `zero_division`, etc.

### Issue 2: skore UI does not like NaN apparently

In the example above, I still try to show the `CrossValidateReporter` in the UI and I get:

![image](https://github.com/user-attachments/assets/3736e85e-83d4-4cea-bea7-69c1ec0ff901)

I assume that it does not expect some of the internal values of the `_cv_results`?

### Issue 3

In the minimal report, I would expect to add `scoring="accuracy"` and that `skore` does not try anymore to force some metrics on me. But apparently this is not the case. So basically I don't have a way around the issue at this stage.

### Issue 4

I don't get the same results than the scikit-learn call:

```python
from sklearn.model_selection import cross_validate

cv_results = cross_validate(model, X, y, scoring="neg_log_loss", return_estimator=True)
cv_results
```

```
{'fit_time': array([0.01414204, 0.00921512, 0.00733423, 0.00623608, 0.00577497]),
 'score_time': array([0.0018239 , 0.00107193, 0.00116467, 0.00092483, 0.00074506]),
 'estimator': [LogisticRegression(),
  LogisticRegression(),
  LogisticRegression(),
  LogisticRegression(),
  LogisticRegression()],
 'test_score': array([-0.14686091, -0.10706954, -0.19150266, -0.14837966, -0.10602087])}
```

So it means that there is something magical that we do internally?

**Comment by MarieS-WiMLDS** [comment]
the last point of the original feedback will be tackled in: https://github.com/probabl-ai/skore/issues/1218

**Comment by glemaitre** [comment]
Yep indeed. Everything is fine now apart of the `nan` but there is a dedicated issue. Thanks for triaging.
