### ISSUE TITLE
docs: In the contributing guide, `make serve-skore-ui` does not work.

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#1026]
### Which part of the documentation needs improvement?

Contributing guide.

### Describe the problem found in the documentation

We state:
```python
make install-skore
make build-skore-ui
make serve-skore-ui
```

However, `make serve-skore-ui` leads to a bug on my side:
```
(.venv) ➜  skore git:(main) make serve-skore-ui
python -m uvicorn \
                --factory skore.ui.app:create_app \
                --reload --reload-dir skore/src \
                --host 0.0.0.0 \
                --port 22140 \
                --timeout-graceful-shutdown 0
INFO:     Will watch for changes in these directories: ['/Users/sylvaincom/Documents/GitHub/skore/skore/src']
INFO:     Uvicorn running on http://0.0.0.0:22140 (Press CTRL+C to quit)
INFO:     Started reloader process [47061] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/anaconda3/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sylvaincom/Documents/GitHub/skore/.venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/sylvaincom/Documents/GitHub/skore/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/sylvaincom/Documents/GitHub/skore/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/sylvaincom/Documents/GitHub/skore/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/sylvaincom/Documents/GitHub/skore/.venv/lib/python3.12/site-packages/uvicorn/config.py", line 440, in load
    self.loaded_app = self.loaded_app()
                      ^^^^^^^^^^^^^^^^^
  File "/Users/sylvaincom/Documents/GitHub/skore/skore/src/skore/ui/app.py", line 24, in create_app
    project = load("project.skore")
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sylvaincom/Documents/GitHub/skore/skore/src/skore/project/load.py", line 30, in load
    raise ProjectLoadError(f"Project '{path}' does not exist: did you create it?")
skore.project.load.ProjectLoadError: Project '/Users/sylvaincom/Documents/GitHub/skore/project.skore' does not exist: did you create it?
```

**Comment by rouk1** [comment]
The command does not create a default project hence it crashes if you have no _project.skore_ in your cwd.

Anyway I recommend to get rid of this makefile helper.
Now we can simply use the cli `python -m skore launch proj`.
