### ISSUE TITLE
skore cli does not work if the user did not install pandas

### ISSUE THREAD

**Issue by rouk1** [probabl-ai/skore#868]
### Describe the bug

If you pip install skore and try to run the cli in a fresh virtual env it crashes.

### Steps/Code to Reproduce

```bash
python3.12 -m venv venv
source ./venv/bin/activate
skore create toto
```

### Expected Behavior

It should not crash.

### Actual Behavior

It crashed with the following traceback.

```pytb
Traceback (most recent call last):
  File "/Users/rouk1/Downloads/deleteme/venv/bin/skore", line 5, in <module>
    from skore.__main__ import main
  File "/Users/rouk1/Downloads/deleteme/venv/lib/python3.12/site-packages/skore/__init__.py", line 8, in <module>
    from skore.sklearn import cross_validate, train_test_split
  File "/Users/rouk1/Downloads/deleteme/venv/lib/python3.12/site-packages/skore/sklearn/__init__.py", line 4, in <module>
    from skore.sklearn.train_test_split.train_test_split import train_test_split
  File "/Users/rouk1/Downloads/deleteme/venv/lib/python3.12/site-packages/skore/sklearn/train_test_split/train_test_split.py", line 13, in <module>
    from skore.sklearn.train_test_split.warning import TRAIN_TEST_SPLIT_WARNINGS
  File "/Users/rouk1/Downloads/deleteme/venv/lib/python3.12/site-packages/skore/sklearn/train_test_split/warning/__init__.py", line 10, in <module>
    from .high_class_imbalance_warning import (
  File "/Users/rouk1/Downloads/deleteme/venv/lib/python3.12/site-packages/skore/sklearn/train_test_split/warning/high_class_imbalance_warning.py", line 10, in <module>
    import pandas
ModuleNotFoundError: No module named 'pandas'
```

### Environment

```shell
skore: 0.4.1
```

**Comment by thomass-dev** [comment]
Already addressed by https://github.com/probabl-ai/skore/pull/867

**Comment by rouk1** [comment]
> Duplicate of #867

whoops my bad
